#!/bin/sh

if [ ! -d $HOME/.dwarffortress ]; then
    mkdir -p $HOME/.dwarffortress/data
    ln -s /usr/share/dwarffortress/raw $HOME/.dwarffortress/raw
    ln -s /usr/share/dwarffortress/libs $HOME/.dwarffortress/libs
    cp -rn /usr/share/dwarffortress/data/init $HOME/.dwarffortress/data/init
fi

for link in announcement art dipscript help index initial_movies movies shader.fs shader.vs sound speech; do
    cp -r /usr/share/dwarffortress/data/$link $HOME/.dwarffortress/data/$link
done

cd $HOME/.dwarffortress
exec ./libs/Dwarf_Fortress $@
