[build]
cargo = "build/x86_64-unknown-linux-gnu/stage0/bin/cargo"
rustc = "build/x86_64-unknown-linux-gnu/stage0/bin/rustc"
python = "python2.7"
extended = true
verbose = 0

[install]
prefix = "/usr"

[rust]
codegen-units = 0
debuginfo = true

channel = "stable"
